name: git action 공부

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 기여자의 브랜치로 checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: node 설정
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "yarn"

      - name: 캐시할 영역 설정
        id: cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Dependencies 설치
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install
          echo "설치!!!"

      - name: ls -al 출력
        run: ls -al

      - name: 변경된 파일에 대한 eslint 실행
        uses: tj-actions/eslint-changed-files@v25
        with:
          config_path: "./eslint.config.mjs"
          extra_args: "--max-warnings=0"

      - name: 출력
        run: echo "Pull Request"
