name: git action 공부

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 기여자의 브랜치로 checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: node 설정
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "yarn"

      - name: 변경된 파일 가져오기
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: 변경된 파일 변수에 담기
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: echo "변경된 파일 리스트 ${{ env.ALL_CHANGED_FILES }}"
